[package]
name = "renderer"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
bevy = { version = "0.14.1", features = ["async-io"] }
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
